export interface Book {
  id: string;
  title: string;
  file: string;
  grade: string;
  type: "PB" | "TG";
  subject: string;
}

export const LIBRARY_BOOKS: Book[] = [
  { id: "p1-english-pb", title: "P1-English-PB", file: "/library/P1 revised Pupils Books  and Teachers Guides 2025-20260511/PB/P1-English-PB.pdf", grade: "P1", type: "PB", subject: "English" },
  { id: "p1-french-(1)-pb", title: "P1-French-PB (1)", file: "/library/P1 revised Pupils Books  and Teachers Guides 2025-20260511/PB/P1-French-PB (1).pdf", grade: "P1", type: "PB", subject: "French  (1)" },
  { id: "p1-kinyarwanda-pb", title: "P1-Kinyarwanda-PB", file: "/library/P1 revised Pupils Books  and Teachers Guides 2025-20260511/PB/P1-Kinyarwanda-PB.pdf", grade: "P1", type: "PB", subject: "Kinyarwanda" },
  { id: "p1-mathematics-pb", title: "P1 Mathematics PB", file: "/library/P1 revised Pupils Books  and Teachers Guides 2025-20260511/PB/P1 Mathematics PB.pdf", grade: "P1", type: "PB", subject: "Mathematics" },
  { id: "p1-set-pb", title: "P1-SET-PB", file: "/library/P1 revised Pupils Books  and Teachers Guides 2025-20260511/PB/P1-SET-PB.pdf", grade: "P1", type: "PB", subject: "SET" },
  { id: "p1-sst-pb", title: "P1-SST-PB", file: "/library/P1 revised Pupils Books  and Teachers Guides 2025-20260511/PB/P1-SST-PB.pdf", grade: "P1", type: "PB", subject: "SST" },
  { id: "p1-creative-arts-tg", title: "P1-Creative Arts-TG", file: "/library/P1 revised Pupils Books  and Teachers Guides 2025-20260511/TG/P1-Creative Arts-TG.pdf", grade: "P1", type: "TG", subject: "Creative Arts" },
  { id: "p1-english-tg", title: "P1-English-TG", file: "/library/P1 revised Pupils Books  and Teachers Guides 2025-20260511/TG/P1-English-TG.pdf", grade: "P1", type: "TG", subject: "English" },
  { id: "p1-french-tg", title: "P1-French-TG", file: "/library/P1 revised Pupils Books  and Teachers Guides 2025-20260511/TG/P1-French-TG.pdf", grade: "P1", type: "TG", subject: "French" },
  { id: "p1-kinyarwanda-tg", title: "P1-Kinyarwanda-TG", file: "/library/P1 revised Pupils Books  and Teachers Guides 2025-20260511/TG/P1-Kinyarwanda-TG.pdf", grade: "P1", type: "TG", subject: "Kinyarwanda" },
  { id: "p1-mathematics-.-tg", title: "P1-Mathematics-TG .", file: "/library/P1 revised Pupils Books  and Teachers Guides 2025-20260511/TG/P1-Mathematics-TG ..pdf", grade: "P1", type: "TG", subject: "Mathematics  ." },
  { id: "p1-pes-tg", title: "P1-PES-TG", file: "/library/P1 revised Pupils Books  and Teachers Guides 2025-20260511/TG/P1-PES-TG.pdf", grade: "P1", type: "TG", subject: "PES" },
  { id: "p1-set-tg", title: "P1-SET-TG", file: "/library/P1 revised Pupils Books  and Teachers Guides 2025-20260511/TG/P1-SET-TG.pdf", grade: "P1", type: "TG", subject: "SET" },
  { id: "p1-sst-.-tg", title: "P1-SST-TG.", file: "/library/P1 revised Pupils Books  and Teachers Guides 2025-20260511/TG/P1-SST-TG..pdf", grade: "P1", type: "TG", subject: "SST ." },
  { id: "p2-english-pb", title: "P2-English-PB", file: "/library/P2 revised Pupils books B and Teachers Guides  2025-20260511/PB/P2-English-PB.pdf", grade: "P2", type: "PB", subject: "English" },
  { id: "p2-french-pb", title: "P2-French-PB", file: "/library/P2 revised Pupils books B and Teachers Guides  2025-20260511/PB/P2-French-PB.pdf", grade: "P2", type: "PB", subject: "French" },
  { id: "p2-kinyarwanda-pb", title: "P2-Kinyarwanda-PB", file: "/library/P2 revised Pupils books B and Teachers Guides  2025-20260511/PB/P2-Kinyarwanda-PB.pdf", grade: "P2", type: "PB", subject: "Kinyarwanda" },
  { id: "p2-mathematics-pb", title: "P2 Mathematics PB", file: "/library/P2 revised Pupils books B and Teachers Guides  2025-20260511/PB/P2 Mathematics PB.pdf", grade: "P2", type: "PB", subject: "Mathematics" },
  { id: "p2-set-pb", title: "P2-SET-PB", file: "/library/P2 revised Pupils books B and Teachers Guides  2025-20260511/PB/P2-SET-PB.pdf", grade: "P2", type: "PB", subject: "SET" },
  { id: "p2-sst-pb", title: "P2-SST-PB", file: "/library/P2 revised Pupils books B and Teachers Guides  2025-20260511/PB/P2-SST-PB.pdf", grade: "P2", type: "PB", subject: "SST" },
  { id: "p2-creative-arts-tg", title: "P2-Creative Arts-TG", file: "/library/P2 revised Pupils books B and Teachers Guides  2025-20260511/TG/P2-Creative Arts-TG.pdf", grade: "P2", type: "TG", subject: "Creative Arts" },
  { id: "p2-english-tg", title: "P2-English-TG", file: "/library/P2 revised Pupils books B and Teachers Guides  2025-20260511/TG/P2-English-TG.pdf", grade: "P2", type: "TG", subject: "English" },
  { id: "p2-french-tg", title: "P2-french-TG", file: "/library/P2 revised Pupils books B and Teachers Guides  2025-20260511/TG/P2-french-TG.pdf", grade: "P2", type: "TG", subject: "French" },
  { id: "p2-kinyarwanda-tg", title: "P2-Kinyarwanda-TG", file: "/library/P2 revised Pupils books B and Teachers Guides  2025-20260511/TG/P2-Kinyarwanda-TG.pdf", grade: "P2", type: "TG", subject: "Kinyarwanda" },
  { id: "p2-mathematics-tg", title: "P2 Mathematics TG", file: "/library/P2 revised Pupils books B and Teachers Guides  2025-20260511/TG/P2 Mathematics TG.pdf", grade: "P2", type: "TG", subject: "Mathematics" },
  { id: "p2-pes-tg", title: "P2-PES-TG", file: "/library/P2 revised Pupils books B and Teachers Guides  2025-20260511/TG/P2-PES-TG.pdf", grade: "P2", type: "TG", subject: "PES" },
  { id: "p2-set-tg", title: "P2-SET-TG", file: "/library/P2 revised Pupils books B and Teachers Guides  2025-20260511/TG/P2-SET-TG.pdf", grade: "P2", type: "TG", subject: "SET" },
  { id: "p2-sst-tg", title: "P2-SST-TG", file: "/library/P2 revised Pupils books B and Teachers Guides  2025-20260511/TG/P2-SST-TG.pdf", grade: "P2", type: "TG", subject: "SST" },
  { id: "p3-english-pb", title: "P3-English-PB", file: "/library/P3 revised Pupils Books  and Teachers Guides 2025-20260511/PB/P3-English-PB.pdf", grade: "P3", type: "PB", subject: "English" },
  { id: "p3-french-pb", title: "P3-French-PB", file: "/library/P3 revised Pupils Books  and Teachers Guides 2025-20260511/PB/P3-French-PB.pdf", grade: "P3", type: "PB", subject: "French" },
  { id: "p3-kinyarwanda-pb", title: "P3-Kinyarwanda-PB", file: "/library/P3 revised Pupils Books  and Teachers Guides 2025-20260511/PB/P3-Kinyarwanda-PB.pdf", grade: "P3", type: "PB", subject: "Kinyarwanda" },
  { id: "p3-mathematics-pb", title: "P3 Mathematics PB", file: "/library/P3 revised Pupils Books  and Teachers Guides 2025-20260511/PB/P3 Mathematics PB.pdf", grade: "P3", type: "PB", subject: "Mathematics" },
  { id: "p3-set-pb", title: "P3-SET-PB", file: "/library/P3 revised Pupils Books  and Teachers Guides 2025-20260511/PB/P3-SET-PB.pdf", grade: "P3", type: "PB", subject: "SET" },
  { id: "p3-sst-pb", title: "P3-SST-PB", file: "/library/P3 revised Pupils Books  and Teachers Guides 2025-20260511/PB/P3-SST-PB.pdf", grade: "P3", type: "PB", subject: "SST" },
  { id: "p3-creative-arts-tg", title: "P3-Creative Arts-TG", file: "/library/P3 revised Pupils Books  and Teachers Guides 2025-20260511/TG/P3-Creative Arts-TG.pdf", grade: "P3", type: "TG", subject: "Creative Arts" },
  { id: "p3-english-tg", title: "P3-English-TG", file: "/library/P3 revised Pupils Books  and Teachers Guides 2025-20260511/TG/P3-English-TG.pdf", grade: "P3", type: "TG", subject: "English" },
  { id: "p3-french-tg", title: "P3-French-TG", file: "/library/P3 revised Pupils Books  and Teachers Guides 2025-20260511/TG/P3-French-TG.pdf", grade: "P3", type: "TG", subject: "French" },
  { id: "p3-kinyarwanda-tg", title: "P3-Kinyarwanda-TG", file: "/library/P3 revised Pupils Books  and Teachers Guides 2025-20260511/TG/P3-Kinyarwanda-TG.pdf", grade: "P3", type: "TG", subject: "Kinyarwanda" },
  { id: "p3-mathematics-tg", title: "P3 Mathematics TG", file: "/library/P3 revised Pupils Books  and Teachers Guides 2025-20260511/TG/P3 Mathematics TG.pdf", grade: "P3", type: "TG", subject: "Mathematics" },
  { id: "p3-set-tg", title: "P3-SET-TG", file: "/library/P3 revised Pupils Books  and Teachers Guides 2025-20260511/TG/P3-SET-TG.pdf", grade: "P3", type: "TG", subject: "SET" },
  { id: "p3-sst-tg", title: "P3-SST-TG", file: "/library/P3 revised Pupils Books  and Teachers Guides 2025-20260511/TG/P3-SST-TG.pdf", grade: "P3", type: "TG", subject: "SST" },
  { id: "p4-creative-arts-pb", title: "P4-Creative Arts-PB", file: "/library/P4 revised Pupils Books  and Teachers Guides  2025-20260511/PB/P4-Creative Arts-PB.pdf", grade: "P4", type: "PB", subject: "Creative Arts" },
  { id: "p4-english-pb", title: "P4-ENGLISH-PB", file: "/library/P4 revised Pupils Books  and Teachers Guides  2025-20260511/PB/P4-ENGLISH-PB.pdf", grade: "P4", type: "PB", subject: "ENGLISH" },
  { id: "p4-french-pb", title: "P4-French-PB", file: "/library/P4 revised Pupils Books  and Teachers Guides  2025-20260511/PB/P4-French-PB.pdf", grade: "P4", type: "PB", subject: "French" },
  { id: "p4-kinyarwanda-pb", title: "P4-Kinyarwanda-PB", file: "/library/P4 revised Pupils Books  and Teachers Guides  2025-20260511/PB/P4-Kinyarwanda-PB.pdf", grade: "P4", type: "PB", subject: "Kinyarwanda" },
  { id: "p4-mathematics-pb", title: "P4 Mathematics PB", file: "/library/P4 revised Pupils Books  and Teachers Guides  2025-20260511/PB/P4 Mathematics PB.pdf", grade: "P4", type: "PB", subject: "Mathematics" },
  { id: "p4-set-pb", title: "P4-SET-PB", file: "/library/P4 revised Pupils Books  and Teachers Guides  2025-20260511/PB/P4-SET-PB.pdf", grade: "P4", type: "PB", subject: "SET" },
  { id: "p4-sst-(1)-pb", title: "P4-SST-PB (1)", file: "/library/P4 revised Pupils Books  and Teachers Guides  2025-20260511/PB/P4-SST-PB (1).pdf", grade: "P4", type: "PB", subject: "SST  (1)" },
  { id: "p4-creative-arts-tg", title: "P4-Creative Arts-TG ", file: "/library/P4 revised Pupils Books  and Teachers Guides  2025-20260511/TG/P4-Creative Arts-TG .pdf", grade: "P4", type: "TG", subject: "Creative Arts" },
  { id: "p4-english-tg", title: "P4-ENGLISH-TG", file: "/library/P4 revised Pupils Books  and Teachers Guides  2025-20260511/TG/P4-ENGLISH-TG.pdf", grade: "P4", type: "TG", subject: "ENGLISH" },
  { id: "p4-french-tg", title: "P4-French-TG", file: "/library/P4 revised Pupils Books  and Teachers Guides  2025-20260511/TG/P4-French-TG.pdf", grade: "P4", type: "TG", subject: "French" },
  { id: "p4-kinyarwanda-tg", title: "P4-kinyarwanda-TG", file: "/library/P4 revised Pupils Books  and Teachers Guides  2025-20260511/TG/P4-kinyarwanda-TG.pdf", grade: "P4", type: "TG", subject: "Kinyarwanda" },
  { id: "p4-mathematics-tg", title: "P4 Mathematics TG", file: "/library/P4 revised Pupils Books  and Teachers Guides  2025-20260511/TG/P4 Mathematics TG.pdf", grade: "P4", type: "TG", subject: "Mathematics" },
  { id: "p4-pes-tg", title: "P4-PES-TG", file: "/library/P4 revised Pupils Books  and Teachers Guides  2025-20260511/TG/P4-PES-TG.pdf", grade: "P4", type: "TG", subject: "PES" },
  { id: "p4-set-tg", title: "P4-SET-TG", file: "/library/P4 revised Pupils Books  and Teachers Guides  2025-20260511/TG/P4-SET-TG.pdf", grade: "P4", type: "TG", subject: "SET" },
  { id: "p4-sst-(1)-tg", title: "P4-SST-TG (1)", file: "/library/P4 revised Pupils Books  and Teachers Guides  2025-20260511/TG/P4-SST-TG (1).pdf", grade: "P4", type: "TG", subject: "SST  (1)" },
  { id: "p5-creative-arts-pb", title: "P5-Creative Arts-PB", file: "/library/P5 revised  Pupils Books  and Teachers Guides  2025-20260511/PB/P5-Creative Arts-PB.pdf", grade: "P5", type: "PB", subject: "Creative Arts" },
  { id: "p5-english-pb", title: "P5-ENGLISH-PB", file: "/library/P5 revised  Pupils Books  and Teachers Guides  2025-20260511/PB/P5-ENGLISH-PB.pdf", grade: "P5", type: "PB", subject: "ENGLISH" },
  { id: "p5-french-pb", title: "P5-French-PB", file: "/library/P5 revised  Pupils Books  and Teachers Guides  2025-20260511/PB/P5-French-PB.pdf", grade: "P5", type: "PB", subject: "French" },
  { id: "p5-kinyarwanda-pb", title: "P5-Kinyarwanda-PB", file: "/library/P5 revised  Pupils Books  and Teachers Guides  2025-20260511/PB/P5-Kinyarwanda-PB.pdf", grade: "P5", type: "PB", subject: "Kinyarwanda" },
  { id: "p5-mathematics-pb", title: "P5-Mathematics-PB", file: "/library/P5 revised  Pupils Books  and Teachers Guides  2025-20260511/PB/P5-Mathematics-PB.pdf", grade: "P5", type: "PB", subject: "Mathematics" },
  { id: "p5-set-pb", title: "P5-SET-PB", file: "/library/P5 revised  Pupils Books  and Teachers Guides  2025-20260511/PB/P5-SET-PB.pdf", grade: "P5", type: "PB", subject: "SET" },
  { id: "p5-sst-(2)-pb", title: "P5-SST-PB (2)", file: "/library/P5 revised  Pupils Books  and Teachers Guides  2025-20260511/PB/P5-SST-PB (2).pdf", grade: "P5", type: "PB", subject: "SST  (2)" },
  { id: "p5-creative-arts-tg", title: "P5-Creative Arts-TG", file: "/library/P5 revised  Pupils Books  and Teachers Guides  2025-20260511/TG/P5-Creative Arts-TG.pdf", grade: "P5", type: "TG", subject: "Creative Arts" },
  { id: "p5-english-tg", title: "P5-ENGLISH-TG", file: "/library/P5 revised  Pupils Books  and Teachers Guides  2025-20260511/TG/P5-ENGLISH-TG.pdf", grade: "P5", type: "TG", subject: "ENGLISH" },
  { id: "p5-french-tg", title: "P5_French-TG", file: "/library/P5 revised  Pupils Books  and Teachers Guides  2025-20260511/TG/P5_French-TG.pdf", grade: "P5", type: "TG", subject: "French" },
  { id: "p5-kinyarwanda-tg", title: "P5-Kinyarwanda-TG", file: "/library/P5 revised  Pupils Books  and Teachers Guides  2025-20260511/TG/P5-Kinyarwanda-TG.pdf", grade: "P5", type: "TG", subject: "Kinyarwanda" },
  { id: "p5-mathematics-tg", title: "P5-Mathematics-TG", file: "/library/P5 revised  Pupils Books  and Teachers Guides  2025-20260511/TG/P5-Mathematics-TG.pdf", grade: "P5", type: "TG", subject: "Mathematics" },
  { id: "p5-pes-tg", title: "P5-PES-TG", file: "/library/P5 revised  Pupils Books  and Teachers Guides  2025-20260511/TG/P5-PES-TG.pdf", grade: "P5", type: "TG", subject: "PES" },
  { id: "p5-set-tg", title: "P5-SET-TG", file: "/library/P5 revised  Pupils Books  and Teachers Guides  2025-20260511/TG/P5-SET-TG.pdf", grade: "P5", type: "TG", subject: "SET" },
  { id: "p5-sst-tg", title: "P5-SST-TG", file: "/library/P5 revised  Pupils Books  and Teachers Guides  2025-20260511/TG/P5-SST-TG.pdf", grade: "P5", type: "TG", subject: "SST" },
  { id: "p6-creative-arts-pb", title: "P6-Creative Arts-PB", file: "/library/P6 revised Pupils Books and Teachers Guides 2025-20260511/PB/P6-Creative Arts-PB.pdf", grade: "P6", type: "PB", subject: "Creative Arts" },
  { id: "p6-english-pb", title: "P6-ENGLISH-PB", file: "/library/P6 revised Pupils Books and Teachers Guides 2025-20260511/PB/P6-ENGLISH-PB.pdf", grade: "P6", type: "PB", subject: "ENGLISH" },
  { id: "p6-french-pb", title: "P6-French-PB", file: "/library/P6 revised Pupils Books and Teachers Guides 2025-20260511/PB/P6-French-PB.pdf", grade: "P6", type: "PB", subject: "French" },
  { id: "p6-kinyarwanda-pb", title: "P6-Kinyarwanda-PB", file: "/library/P6 revised Pupils Books and Teachers Guides 2025-20260511/PB/P6-Kinyarwanda-PB.pdf", grade: "P6", type: "PB", subject: "Kinyarwanda" },
  { id: "p6-mathematics-pb", title: "P6 Mathematics PB", file: "/library/P6 revised Pupils Books and Teachers Guides 2025-20260511/PB/P6 Mathematics PB.pdf", grade: "P6", type: "PB", subject: "Mathematics" },
  { id: "p6-set-pb", title: "P6-SET-PB", file: "/library/P6 revised Pupils Books and Teachers Guides 2025-20260511/PB/P6-SET-PB.pdf", grade: "P6", type: "PB", subject: "SET" },
  { id: "p6-sst-(1)-pb", title: "P6-SST-PB (1)", file: "/library/P6 revised Pupils Books and Teachers Guides 2025-20260511/PB/P6-SST-PB (1).pdf", grade: "P6", type: "PB", subject: "SST  (1)" },
  { id: "p6-creative-arts-tg", title: "P6-Creative Arts-TG", file: "/library/P6 revised Pupils Books and Teachers Guides 2025-20260511/TG/P6-Creative Arts-TG.pdf", grade: "P6", type: "TG", subject: "Creative Arts" },
  { id: "p6-english-tg", title: "P6-ENGLISH-TG", file: "/library/P6 revised Pupils Books and Teachers Guides 2025-20260511/TG/P6-ENGLISH-TG.pdf", grade: "P6", type: "TG", subject: "ENGLISH" },
  { id: "p6-french-tg", title: "P6-French-TG", file: "/library/P6 revised Pupils Books and Teachers Guides 2025-20260511/TG/P6-French-TG.pdf", grade: "P6", type: "TG", subject: "French" },
  { id: "p6-kinyarwanda-tg", title: "P6-Kinyarwanda-TG", file: "/library/P6 revised Pupils Books and Teachers Guides 2025-20260511/TG/P6-Kinyarwanda-TG.pdf", grade: "P6", type: "TG", subject: "Kinyarwanda" },
  { id: "p6-mathematics-tg", title: "P6 Mathematics TG", file: "/library/P6 revised Pupils Books and Teachers Guides 2025-20260511/TG/P6 Mathematics TG.pdf", grade: "P6", type: "TG", subject: "Mathematics" },
  { id: "p6-pes-tg", title: "P6-PES-TG", file: "/library/P6 revised Pupils Books and Teachers Guides 2025-20260511/TG/P6-PES-TG.pdf", grade: "P6", type: "TG", subject: "PES" },
  { id: "p6-set-tg", title: "P6-SET-TG", file: "/library/P6 revised Pupils Books and Teachers Guides 2025-20260511/TG/P6-SET-TG.pdf", grade: "P6", type: "TG", subject: "SET" },
  { id: "p6-sst-(4)-tg", title: "P6-SST-TG (4)", file: "/library/P6 revised Pupils Books and Teachers Guides 2025-20260511/TG/P6-SST-TG (4).pdf", grade: "P6", type: "TG", subject: "SST  (4)" },
];

export const getBooksByGrade = (grade: string) => LIBRARY_BOOKS.filter(b => b.grade === grade && b.type === "PB");
export const getTeachersGuides = () => LIBRARY_BOOKS.filter(b => b.type === "TG");
