export const VIDEOS = [
  // ═══════════════════════════════════════════════════════════════
  // ── MATHEMATICS (30 VIDEOS) ──
  // ═══════════════════════════════════════════════════════════════
  { id: "8bEygfbxxwI", title: "REB/P3 Math: Fun With Sharing", subject: "Math", level: "P3", duration: "5m", teacherRecommended: true },
  { id: "gKPQp8Btw6Y", title: "REB/P1 Math: Fun With Sharing", subject: "Math", level: "P1", duration: "5m", teacherRecommended: true },
  { id: "XbaQyoQnHlw", title: "REB/P2 Math: The Garden Thief (Animation)", subject: "Math", level: "P2", duration: "7m", teacherRecommended: true },
  { id: "dBzwsq7Ei7c", title: "REB/P4 Math: Positive and Negative Integers", subject: "Math", level: "P4", duration: "12m", teacherRecommended: true },
  { id: "3zsNom7t8bI", title: "Fractions for Beginners (Math Antics)", subject: "Math", level: "P3", duration: "9m", teacherRecommended: true },
  { id: "eW2dRLyVMUQ", title: "Multiplication Tables 1–10 Foundations", subject: "Math", level: "P2", duration: "10m", teacherRecommended: true },
  { id: "dpzMKV3UeCQ", title: "Basic Multiplication Mechanics", subject: "Math", level: "P3", duration: "11m", teacherRecommended: false },
  { id: "q3M31bX2Vsg", title: "Long Division Step-by-Step", subject: "Math", level: "P5", duration: "11m", teacherRecommended: true },
  { id: "NybHckSEQBI", title: "Intro to Algebra & Variables", subject: "Math", level: "P6", duration: "12m", teacherRecommended: true },
  { id: "JeVSmq1Nrpw", title: "What Are Percentages? Basics", subject: "Math", level: "P5", duration: "10m", teacherRecommended: false },
  { id: "ViAmQivKif0", title: "Counting to 100 with Numberblocks", subject: "Math", level: "P1", duration: "7m", teacherRecommended: true },
  { id: "yMc8217w9v4", title: "Addition & Subtraction Essentials", subject: "Math", level: "P2", duration: "8m", teacherRecommended: false },
  { id: "IGGnnKbCAYk", title: "Telling Time & Reading Clocks", subject: "Math", level: "P2", duration: "9m", teacherRecommended: true },
  { id: "T5Qf0qSSJFI", title: "Area and Perimeter Foundations", subject: "Math", level: "P4", duration: "10m", teacherRecommended: true },
  { id: "1vs9rQjVDas", title: "Place Value for Beginners", subject: "Math", level: "P1", duration: "6m", teacherRecommended: true },
  { id: "oqMl7QbXxoE", title: "Shapes and Geometry Fundamentals", subject: "Math", level: "P2", duration: "8m", teacherRecommended: false },
  { id: "OmJ-4B-mS-Y", title: "Understanding Decimals & Place Value", subject: "Math", level: "P4", duration: "9m", teacherRecommended: true },
  { id: "bQ-KR3clFgs", title: "Visualizing Fractions Parts", subject: "Math", level: "P3", duration: "8m", teacherRecommended: true },
  { id: "8pULMUqO87g", title: "Mean, Median & Mode Introduction", subject: "Math", level: "P6", duration: "9m", teacherRecommended: false },
  { id: "aNOFAVtaB3s", title: "Rounding Numbers to Nearest 10 & 100", subject: "Math", level: "P3", duration: "6m", teacherRecommended: false },
  { id: "AS9J_J6EWJI", title: "Multiplication and Division Relationships", subject: "Math", level: "P3", duration: "7m", teacherRecommended: true },
  { id: "nTn9gVqRfKY", title: "Negative Numbers on a Number Line", subject: "Math", level: "P5", duration: "7m", teacherRecommended: false },
  { id: "qmfXyR7Z6Lk", title: "Multiplying Fractions Concepts", subject: "Math", level: "P5", duration: "6m", teacherRecommended: true },
  { id: "4lkq3DgvmJo", title: "Dividing Fractions Made Easy", subject: "Math", level: "P5", duration: "5m", teacherRecommended: true },
  { id: "AtBUQH8Tkqc", title: "Simplifying Fractions Step-by-Step", subject: "Math", level: "P4", duration: "8m", teacherRecommended: false },
  { id: "SZ5RUeXWw2M", title: "Multiplying Mixed Numbers Advanced", subject: "Math", level: "P6", duration: "5m", teacherRecommended: true },
  { id: "Mst8iZjIpFE", title: "Fractions and Decimals Connections", subject: "Math", level: "P4", duration: "9m", teacherRecommended: false },
  { id: "do_IbHId2Os", title: "Convert Any Fraction to a Decimal", subject: "Math", level: "P5", duration: "7m", teacherRecommended: true },
  { id: "_jcW-ZgpRbM", title: "Converting Base-10 Fractions Easily", subject: "Math", level: "P4", duration: "7m", teacherRecommended: false },
  { id: "H2Z4p0_6NoM", title: "Intro to Ratios and Rates", subject: "Math", level: "P6", duration: "8m", teacherRecommended: true },

  // ═══════════════════════════════════════════════════════════════
  // ── SCIENCE (25 VIDEOS) ──
  // ═══════════════════════════════════════════════════════════════
  { id: "D1Ymc311XS8", title: "Photosynthesis Explained (SciShow Kids)", subject: "Science", level: "P4", duration: "5m", teacherRecommended: true },
  { id: "ncORPosDrjI", title: "The Water Cycle Adventure", subject: "Science", level: "P3", duration: "5m", teacherRecommended: true },
  { id: "F2prtmPEjOc", title: "The Solar System (Crash Course Kids)", subject: "Science", level: "P5", duration: "8m", teacherRecommended: true },
  { id: "Pasru_D5Z10", title: "Food Chains & Food Webs Explained", subject: "Science", level: "P4", duration: "5m", teacherRecommended: false },
  { id: "Uf76pThNXZc", title: "Electricity for Kids Basics", subject: "Science", level: "P5", duration: "9m", teacherRecommended: true },
  { id: "JQ4WduVp9k4", title: "States of Matter: Solid, Liquid, Gas", subject: "Science", level: "P3", duration: "6m", teacherRecommended: false },
  { id: "gEUu-A2gBSE", title: "Human Body Systems Tour", subject: "Science", level: "P5", duration: "6m", teacherRecommended: true },
  { id: "WgHmqv_-UbQ", title: "Why Do We Have Seasons? (TED-Ed)", subject: "Science", level: "P4", duration: "5m", teacherRecommended: true },
  { id: "t-xgeAmic-o", title: "What is Gravity? Concepts", subject: "Science", level: "P4", duration: "4m", teacherRecommended: true },
  { id: "GZ5gIE3hE1U", title: "How Magnets Work: Magnetic Fields", subject: "Science", level: "P3", duration: "4m", teacherRecommended: true },
  { id: "wxjmvCsWyL0", title: "Plants, Seeds & Germination", subject: "Science", level: "P2", duration: "6m", teacherRecommended: false },
  { id: "BEdfwxKCSPc", title: "The Human Skeleton Anatomy", subject: "Science", level: "P4", duration: "7m", teacherRecommended: true },
  { id: "1Q_4HXewiS0", title: "Air & Atmosphere Properties", subject: "Science", level: "P3", duration: "5m", teacherRecommended: false },
  { id: "hGwG--GZEfw", title: "How Volcanoes Work & Erupt", subject: "Science", level: "P5", duration: "5m", teacherRecommended: true },
  { id: "n1jC9BGzKfk", title: "Sound Waves & Vibrations", subject: "Science", level: "P3", duration: "4m", teacherRecommended: false },
  { id: "V4fJb8bsVvA", title: "The Life Cycle of a Butterfly", subject: "Science", level: "P2", duration: "4m", teacherRecommended: true },
  { id: "3kdArgpBFoE", title: "What Makes Rainbows? Light Science", subject: "Science", level: "P2", duration: "3m", teacherRecommended: false },
  { id: "ZdqqzHlkyD8", title: "Ecosystems & Habitats Systems", subject: "Science", level: "P5", duration: "8m", teacherRecommended: true },
  { id: "e-snVHBqQME", title: "Light & Shadow Science Basics", subject: "Science", level: "P3", duration: "5m", teacherRecommended: false },
  { id: "lnm6UUbQ5_c", title: "Forces: Push and Pull Introduction", subject: "Science", level: "P1", duration: "5m", teacherRecommended: true },
  { id: "6JB0LCPJ0o8", title: "Animals & Their Habitats Map", subject: "Science", level: "P2", duration: "6m", teacherRecommended: true },
  { id: "XCzFE0SB2N4", title: "Deep Dive into Photosynthesis", subject: "Science", level: "P5", duration: "5m", teacherRecommended: true },
  { id: "V863xR0Y2qk", title: "Introduction to Volcanoes and Magma", subject: "Science", level: "P4", duration: "7m", teacherRecommended: false },
  { id: "RubnGwhcT6E", title: "The Milky Way Galaxy Exploration", subject: "Science", level: "P6", duration: "5m", teacherRecommended: true },
  { id: "m2MibjJgyjs", title: "Animal Adaptations Overview", subject: "Science", level: "P5", duration: "8m", teacherRecommended: true },

  // ═══════════════════════════════════════════════════════════════
  // ── ENGLISH (20 VIDEOS) ──
  // ═══════════════════════════════════════════════════════════════
  { id: "jQgmLrvmnmI", title: "REB/P1 English: Classroom Objects", subject: "English", level: "P1", duration: "4m", teacherRecommended: true },
  { id: "hq3yfQnllfQ", title: "Alphablocks: Learn to Read Phonics", subject: "English", level: "P1", duration: "24m", teacherRecommended: true },
  { id: "75p-N9YKqNo", title: "Nouns, Verbs & Adjectives Fun", subject: "English", level: "P3", duration: "10m", teacherRecommended: true },
  { id: "LdCOswQLOUU", title: "Punctuation Song for Kids", subject: "English", level: "P3", duration: "4m", teacherRecommended: false },
  { id: "3v8TTiobAnI", title: "Short Stories for Reading Practice", subject: "English", level: "P2", duration: "18m", teacherRecommended: true },
  { id: "OWJCflt6CYA", title: "English Vocabulary Games", subject: "English", level: "P4", duration: "7m", teacherRecommended: true },
  { id: "h4QEzJEgntc", title: "Eight Parts of Speech Explained", subject: "English", level: "P5", duration: "8m", teacherRecommended: false },
  { id: "QGkcqup4fUo", title: "Grammar Basics: Sentences & Syntax", subject: "English", level: "P4", duration: "58m", teacherRecommended: true },
  { id: "zVu-XvULZNg", title: "13 Basic Punctuation Rules Guide", subject: "English", level: "P6", duration: "18m", teacherRecommended: true },
  { id: "4IqlgGLV1XQ", title: "Advanced Writing: Commas & Colons", subject: "English", level: "P6", duration: "19m", teacherRecommended: false },
  { id: "0l69KEx7GQo", title: "Parts of Speech Comprehensive Guide", subject: "English", level: "P3", duration: "6m", teacherRecommended: true },
  { id: "SceDmiBEESI", title: "Sentence Structure Foundations", subject: "English", level: "P5", duration: "20m", teacherRecommended: false },
  { id: "27O9_92Kkqw", title: "Singular and Plural Nouns Lessons", subject: "English", level: "P2", duration: "6m", teacherRecommended: true },
  { id: "wPM8vCoVpWk", title: "Introduction to Pronouns for Kids", subject: "English", level: "P2", duration: "5m", teacherRecommended: false },
  { id: "m9I-v9w8N-o", title: "Understanding Synonyms & Antonyms", subject: "English", level: "P4", duration: "7m", teacherRecommended: true },
  { id: "xk47dK4P9v0", title: "Present Tense vs. Past Tense Verbs", subject: "English", level: "P3", duration: "8m", teacherRecommended: true },
  { id: "U7mK8gAOUwM", title: "Reading Comprehension Strategies", subject: "English", level: "P5", duration: "10m", teacherRecommended: true },
  { id: "F8XbZ2P2w0M", title: "How to Write a Paragraph Structure", subject: "English", level: "P5", duration: "9m", teacherRecommended: false },
  { id: "Zf0v2p4K0Mo", title: "Prefixes and Suffixes Meanings", subject: "English", level: "P4", duration: "6m", teacherRecommended: true },
  { id: "E6VpM3W9w8o", title: "Idioms & Metaphors for Young Writers", subject: "English", level: "P6", duration: "8m", teacherRecommended: false },

  // ═══════════════════════════════════════════════════════════════
  // ── KINYARWANDA (13 VIDEOS) ──
  // ═══════════════════════════════════════════════════════════════
  { id: "SEuT8ERQAOA", title: "REB/P4 Kinyarwanda: Ibintu 10 Nkunda", subject: "Kinyarwanda", level: "P4", duration: "3m", teacherRecommended: true },
  { id: "jIfzzI4dPTQ", title: "REB/P1 Kinyarwanda: Nkunda Imineke Rhyme", subject: "Kinyarwanda", level: "P1", duration: "4m", teacherRecommended: true },
  { id: "anfusVIduSo", title: "REB/P2 Kinyarwanda: Sakwe Sakwe Riddles", subject: "Kinyarwanda", level: "P2", duration: "5m", teacherRecommended: true },
  { id: "YFzwirfeEiI", title: "Kinyarwanda Language Basics & Greetings", subject: "Kinyarwanda", level: "P1", duration: "10m", teacherRecommended: true },
  { id: "D3-MkKBhFWA", title: "Ubongo Kids: Ikinyarwanda Stories", subject: "Kinyarwanda", level: "P1", duration: "12m", teacherRecommended: true },
  { id: "aekTVaRhAD4", title: "Akili and Me: Amasomo yo Gusoma", subject: "Kinyarwanda", level: "P1", duration: "15m", teacherRecommended: true },
  { id: "9Yf9nGWqyDs", title: "Imigani: Rwandan Proverbs & Stories", subject: "Kinyarwanda", level: "P4", duration: "8m", teacherRecommended: false },
  { id: "Wba3T7m_Uto", title: "Ubongo Kids Kinyarwanda: Nshuti Zacu", subject: "Kinyarwanda", level: "P2", duration: "11m", teacherRecommended: true },
  { id: "lRInbH9hZ3E", title: "Igisakuzo Nyarwanda - Traditional Riddles", subject: "Kinyarwanda", level: "P4", duration: "6m", teacherRecommended: true },
  { id: "dWfCKdn46iE", title: "Learn Swahili & Kinyarwanda Vocabulary", subject: "Kinyarwanda", level: "P2", duration: "2m", teacherRecommended: false },
  { id: "m2bKwO09w7A", title: "Gusoma Amagambo n'Interuro (P1)", subject: "Kinyarwanda", level: "P1", duration: "8m", teacherRecommended: true },
  { id: "K9Wp2N_Z8oA", title: "Umuco n'Imigenzo Nyarwanda Lessons", subject: "Kinyarwanda", level: "P5", duration: "12m", teacherRecommended: true },
  { id: "Z7xV0p29kM4", title: "Inshinga n'Ikibonezamvugo cy'Ikinyarwanda", subject: "Kinyarwanda", level: "P6", duration: "14m", teacherRecommended: false },

  // ═══════════════════════════════════════════════════════════════
  // ── SOCIAL STUDIES (12 VIDEOS) ──
  // ═══════════════════════════════════════════════════════════════
  { id: "jXqiXx1GFCg", title: "REB/P1 SST: A Day At Parliament Visit", subject: "Social", level: "P1", duration: "6m", teacherRecommended: true },
  { id: "Vq8v-Cv7GnY", title: "REB/P3 SST: A Trip to the Sector", subject: "Social", level: "P3", duration: "7m", teacherRecommended: true },
  { id: "Yocja_N5s2I", title: "History of Rwanda Comprehensive Overview", subject: "Social", level: "P6", duration: "14m", teacherRecommended: true },
  { id: "Kz69f1V9qLI", title: "Geography of Africa for Students", subject: "Social", level: "P5", duration: "10m", teacherRecommended: true },
  { id: "O3tY1T6598c", title: "How Governments Work & Civic Duties", subject: "Social", level: "P6", duration: "9m", teacherRecommended: false },
  { id: "mOJlg8g8_yw", title: "Geopolitics of East African Community", subject: "Social", level: "P6", duration: "12m", teacherRecommended: true },
  { id: "A2w589bO3uM", title: "Ancient Civilizations World History", subject: "Social", level: "P5", duration: "11m", teacherRecommended: false },
  { id: "2hSgI2gX0gM", title: "East African EAC Landmarks & Maps", subject: "Social", level: "P6", duration: "8m", teacherRecommended: true },
  { id: "_8wqX2xsjHI", title: "Ubongo Kids: Wakati ni Mali Lessons", subject: "Social", level: "P4", duration: "10m", teacherRecommended: true },
  { id: "E0trLsGKTCA", title: "Tunalisha Ulimwengu: Market Economics", subject: "Social", level: "P5", duration: "29m", teacherRecommended: true },
  { id: "W9oXp2K0mZ8", title: "Maps and Cardinal Directions Basics", subject: "Social", level: "P2", duration: "6m", teacherRecommended: true },
  { id: "L4p9vW02mXk", title: "Our Community and Local Leaders", subject: "Social", level: "P3", duration: "8m", teacherRecommended: false },
];
