/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudentRouteImport } from './routes/student'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IslandRouteImport } from './routes/island'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as TeacherStudentsRouteImport } from './routes/teacher.students'
import { Route as TeacherReportsRouteImport } from './routes/teacher.reports'
import { Route as TeacherAssignmentsRouteImport } from './routes/teacher.assignments'
import { Route as TeacherAlertsRouteImport } from './routes/teacher.alerts'
import { Route as StudentVideosRouteImport } from './routes/student.videos'
import { Route as StudentTutorRouteImport } from './routes/student.tutor'
import { Route as StudentSpeakRouteImport } from './routes/student.speak'
import { Route as StudentSimplifyRouteImport } from './routes/student.simplify'
import { Route as StudentReadRouteImport } from './routes/student.read'
import { Route as StudentQuizzesRouteImport } from './routes/student.quizzes'
import { Route as StudentProgressRouteImport } from './routes/student.progress'
import { Route as StudentPlannerRouteImport } from './routes/student.planner'
import { Route as StudentLibraryRouteImport } from './routes/student.library'
import { Route as StudentHomeworkRouteImport } from './routes/student.homework'
import { Route as StudentGamesRouteImport } from './routes/student.games'
import { Route as StudentCommunityRouteImport } from './routes/student.community'
import { Route as StudentCareerRouteImport } from './routes/student.career'
import { Route as StudentAiQuizzesRouteImport } from './routes/student.ai-quizzes'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IslandRoute = IslandRouteImport.update({
  id: '/island',
  path: '/island',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const TeacherStudentsRoute = TeacherStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherReportsRoute = TeacherReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAssignmentsRoute = TeacherAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAlertsRoute = TeacherAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentVideosRoute = StudentVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => StudentRoute,
} as any)
const StudentTutorRoute = StudentTutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => StudentRoute,
} as any)
const StudentSpeakRoute = StudentSpeakRouteImport.update({
  id: '/speak',
  path: '/speak',
  getParentRoute: () => StudentRoute,
} as any)
const StudentSimplifyRoute = StudentSimplifyRouteImport.update({
  id: '/simplify',
  path: '/simplify',
  getParentRoute: () => StudentRoute,
} as any)
const StudentReadRoute = StudentReadRouteImport.update({
  id: '/read',
  path: '/read',
  getParentRoute: () => StudentRoute,
} as any)
const StudentQuizzesRoute = StudentQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProgressRoute = StudentProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => StudentRoute,
} as any)
const StudentPlannerRoute = StudentPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => StudentRoute,
} as any)
const StudentLibraryRoute = StudentLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => StudentRoute,
} as any)
const StudentHomeworkRoute = StudentHomeworkRouteImport.update({
  id: '/homework',
  path: '/homework',
  getParentRoute: () => StudentRoute,
} as any)
const StudentGamesRoute = StudentGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCommunityRoute = StudentCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCareerRoute = StudentCareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAiQuizzesRoute = StudentAiQuizzesRouteImport.update({
  id: '/ai-quizzes',
  path: '/ai-quizzes',
  getParentRoute: () => StudentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/island': typeof IslandRoute
  '/login': typeof LoginRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/student/ai-quizzes': typeof StudentAiQuizzesRoute
  '/student/career': typeof StudentCareerRoute
  '/student/community': typeof StudentCommunityRoute
  '/student/games': typeof StudentGamesRoute
  '/student/homework': typeof StudentHomeworkRoute
  '/student/library': typeof StudentLibraryRoute
  '/student/planner': typeof StudentPlannerRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/quizzes': typeof StudentQuizzesRoute
  '/student/read': typeof StudentReadRoute
  '/student/simplify': typeof StudentSimplifyRoute
  '/student/speak': typeof StudentSpeakRoute
  '/student/tutor': typeof StudentTutorRoute
  '/student/videos': typeof StudentVideosRoute
  '/teacher/alerts': typeof TeacherAlertsRoute
  '/teacher/assignments': typeof TeacherAssignmentsRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/island': typeof IslandRoute
  '/login': typeof LoginRoute
  '/student/ai-quizzes': typeof StudentAiQuizzesRoute
  '/student/career': typeof StudentCareerRoute
  '/student/community': typeof StudentCommunityRoute
  '/student/games': typeof StudentGamesRoute
  '/student/homework': typeof StudentHomeworkRoute
  '/student/library': typeof StudentLibraryRoute
  '/student/planner': typeof StudentPlannerRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/quizzes': typeof StudentQuizzesRoute
  '/student/read': typeof StudentReadRoute
  '/student/simplify': typeof StudentSimplifyRoute
  '/student/speak': typeof StudentSpeakRoute
  '/student/tutor': typeof StudentTutorRoute
  '/student/videos': typeof StudentVideosRoute
  '/teacher/alerts': typeof TeacherAlertsRoute
  '/teacher/assignments': typeof TeacherAssignmentsRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/island': typeof IslandRoute
  '/login': typeof LoginRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/student/ai-quizzes': typeof StudentAiQuizzesRoute
  '/student/career': typeof StudentCareerRoute
  '/student/community': typeof StudentCommunityRoute
  '/student/games': typeof StudentGamesRoute
  '/student/homework': typeof StudentHomeworkRoute
  '/student/library': typeof StudentLibraryRoute
  '/student/planner': typeof StudentPlannerRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/quizzes': typeof StudentQuizzesRoute
  '/student/read': typeof StudentReadRoute
  '/student/simplify': typeof StudentSimplifyRoute
  '/student/speak': typeof StudentSpeakRoute
  '/student/tutor': typeof StudentTutorRoute
  '/student/videos': typeof StudentVideosRoute
  '/teacher/alerts': typeof TeacherAlertsRoute
  '/teacher/assignments': typeof TeacherAssignmentsRoute
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/island'
    | '/login'
    | '/student'
    | '/teacher'
    | '/student/ai-quizzes'
    | '/student/career'
    | '/student/community'
    | '/student/games'
    | '/student/homework'
    | '/student/library'
    | '/student/planner'
    | '/student/progress'
    | '/student/quizzes'
    | '/student/read'
    | '/student/simplify'
    | '/student/speak'
    | '/student/tutor'
    | '/student/videos'
    | '/teacher/alerts'
    | '/teacher/assignments'
    | '/teacher/reports'
    | '/teacher/students'
    | '/student/'
    | '/teacher/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/island'
    | '/login'
    | '/student/ai-quizzes'
    | '/student/career'
    | '/student/community'
    | '/student/games'
    | '/student/homework'
    | '/student/library'
    | '/student/planner'
    | '/student/progress'
    | '/student/quizzes'
    | '/student/read'
    | '/student/simplify'
    | '/student/speak'
    | '/student/tutor'
    | '/student/videos'
    | '/teacher/alerts'
    | '/teacher/assignments'
    | '/teacher/reports'
    | '/teacher/students'
    | '/student'
    | '/teacher'
  id:
    | '__root__'
    | '/'
    | '/island'
    | '/login'
    | '/student'
    | '/teacher'
    | '/student/ai-quizzes'
    | '/student/career'
    | '/student/community'
    | '/student/games'
    | '/student/homework'
    | '/student/library'
    | '/student/planner'
    | '/student/progress'
    | '/student/quizzes'
    | '/student/read'
    | '/student/simplify'
    | '/student/speak'
    | '/student/tutor'
    | '/student/videos'
    | '/teacher/alerts'
    | '/teacher/assignments'
    | '/teacher/reports'
    | '/teacher/students'
    | '/student/'
    | '/teacher/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IslandRoute: typeof IslandRoute
  LoginRoute: typeof LoginRoute
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/island': {
      id: '/island'
      path: '/island'
      fullPath: '/island'
      preLoaderRoute: typeof IslandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/teacher/students': {
      id: '/teacher/students'
      path: '/students'
      fullPath: '/teacher/students'
      preLoaderRoute: typeof TeacherStudentsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/reports': {
      id: '/teacher/reports'
      path: '/reports'
      fullPath: '/teacher/reports'
      preLoaderRoute: typeof TeacherReportsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/assignments': {
      id: '/teacher/assignments'
      path: '/assignments'
      fullPath: '/teacher/assignments'
      preLoaderRoute: typeof TeacherAssignmentsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/alerts': {
      id: '/teacher/alerts'
      path: '/alerts'
      fullPath: '/teacher/alerts'
      preLoaderRoute: typeof TeacherAlertsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/videos': {
      id: '/student/videos'
      path: '/videos'
      fullPath: '/student/videos'
      preLoaderRoute: typeof StudentVideosRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/tutor': {
      id: '/student/tutor'
      path: '/tutor'
      fullPath: '/student/tutor'
      preLoaderRoute: typeof StudentTutorRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/speak': {
      id: '/student/speak'
      path: '/speak'
      fullPath: '/student/speak'
      preLoaderRoute: typeof StudentSpeakRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/simplify': {
      id: '/student/simplify'
      path: '/simplify'
      fullPath: '/student/simplify'
      preLoaderRoute: typeof StudentSimplifyRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/read': {
      id: '/student/read'
      path: '/read'
      fullPath: '/student/read'
      preLoaderRoute: typeof StudentReadRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/quizzes': {
      id: '/student/quizzes'
      path: '/quizzes'
      fullPath: '/student/quizzes'
      preLoaderRoute: typeof StudentQuizzesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/progress': {
      id: '/student/progress'
      path: '/progress'
      fullPath: '/student/progress'
      preLoaderRoute: typeof StudentProgressRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/planner': {
      id: '/student/planner'
      path: '/planner'
      fullPath: '/student/planner'
      preLoaderRoute: typeof StudentPlannerRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/library': {
      id: '/student/library'
      path: '/library'
      fullPath: '/student/library'
      preLoaderRoute: typeof StudentLibraryRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/homework': {
      id: '/student/homework'
      path: '/homework'
      fullPath: '/student/homework'
      preLoaderRoute: typeof StudentHomeworkRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/games': {
      id: '/student/games'
      path: '/games'
      fullPath: '/student/games'
      preLoaderRoute: typeof StudentGamesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/community': {
      id: '/student/community'
      path: '/community'
      fullPath: '/student/community'
      preLoaderRoute: typeof StudentCommunityRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/career': {
      id: '/student/career'
      path: '/career'
      fullPath: '/student/career'
      preLoaderRoute: typeof StudentCareerRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/ai-quizzes': {
      id: '/student/ai-quizzes'
      path: '/ai-quizzes'
      fullPath: '/student/ai-quizzes'
      preLoaderRoute: typeof StudentAiQuizzesRouteImport
      parentRoute: typeof StudentRoute
    }
  }
}

interface StudentRouteChildren {
  StudentAiQuizzesRoute: typeof StudentAiQuizzesRoute
  StudentCareerRoute: typeof StudentCareerRoute
  StudentCommunityRoute: typeof StudentCommunityRoute
  StudentGamesRoute: typeof StudentGamesRoute
  StudentHomeworkRoute: typeof StudentHomeworkRoute
  StudentLibraryRoute: typeof StudentLibraryRoute
  StudentPlannerRoute: typeof StudentPlannerRoute
  StudentProgressRoute: typeof StudentProgressRoute
  StudentQuizzesRoute: typeof StudentQuizzesRoute
  StudentReadRoute: typeof StudentReadRoute
  StudentSimplifyRoute: typeof StudentSimplifyRoute
  StudentSpeakRoute: typeof StudentSpeakRoute
  StudentTutorRoute: typeof StudentTutorRoute
  StudentVideosRoute: typeof StudentVideosRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAiQuizzesRoute: StudentAiQuizzesRoute,
  StudentCareerRoute: StudentCareerRoute,
  StudentCommunityRoute: StudentCommunityRoute,
  StudentGamesRoute: StudentGamesRoute,
  StudentHomeworkRoute: StudentHomeworkRoute,
  StudentLibraryRoute: StudentLibraryRoute,
  StudentPlannerRoute: StudentPlannerRoute,
  StudentProgressRoute: StudentProgressRoute,
  StudentQuizzesRoute: StudentQuizzesRoute,
  StudentReadRoute: StudentReadRoute,
  StudentSimplifyRoute: StudentSimplifyRoute,
  StudentSpeakRoute: StudentSpeakRoute,
  StudentTutorRoute: StudentTutorRoute,
  StudentVideosRoute: StudentVideosRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherRouteChildren {
  TeacherAlertsRoute: typeof TeacherAlertsRoute
  TeacherAssignmentsRoute: typeof TeacherAssignmentsRoute
  TeacherReportsRoute: typeof TeacherReportsRoute
  TeacherStudentsRoute: typeof TeacherStudentsRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherAlertsRoute: TeacherAlertsRoute,
  TeacherAssignmentsRoute: TeacherAssignmentsRoute,
  TeacherReportsRoute: TeacherReportsRoute,
  TeacherStudentsRoute: TeacherStudentsRoute,
  TeacherIndexRoute: TeacherIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IslandRoute: IslandRoute,
  LoginRoute: LoginRoute,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
